### ISSUE TITLE
[0.17] crashed client on startup

### ISSUE THREAD

**Issue by kreezxil** [DaedalusGame/BetterWithAddons#26]
The crash report says that Iron Chests crashed with a lang exception and further on down says it caused by some japanenese stuff and an npe in better with add ons. I'll post to Iron Chests too just in case.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DummyPlugin (ForgeEndertech-1.11.2-2.1.3.0-build.0067.jar)
  Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  ItemPatchingLoader (ItemPhysic Full 1.4.6 mc1.11.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.92.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  GudLib (gud_lib-1.2.0.0.jar)
  FarseekCoreMod (Farseek-1.11-2.1.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  CreativePatchingLoader (CreativeCore v1.7.4 mc1.11.2.jar)
  llibrary (llibrary-1.7.6-1.11.2.jar)
  LittlePatchingLoader (LittleTiles v1.4.12 mc1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.6.jar)
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  MMFMLCorePlugin (MultiMine-1.11.2.jar)
  literalascension (literalascension-1.11.2-1.0.2.2.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 7/16/17 6:23 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Iron Chest (ironchest)
Caused by: java.lang.ExceptionInInitializerError
	at cpw.mods.ironchest.client.ClientProxy.registerRenderInformation(ClientProxy.java:58)
	at cpw.mods.ironchest.IronChest.preInit(IronChest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at betterwithaddons.handler.JapaneseMobHandler.japaneseAttachCapability(JapaneseMobHandler.java:141)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_105_JapaneseMobHandler_japaneseAttachCapability_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:619)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:589)
	at net.minecraft.entity.Entity.<init>(Entity.java:216)
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:75)
	at cpw.mods.ironchest.client.renderer.chest.TileEntityIronChestRenderer.<clinit>(TileEntityIronChestRenderer.java:43)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 753891632 bytes (718 MB) / 1754791936 bytes (1673 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2393 127 mods loaded, 127 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2393.jar) 
	UCH	forge{13.20.1.2393} [Minecraft Forge] (forge-1.11.2-13.20.1.2393.jar) 
	UCH	ColorUtility{1.0.4} [ColorUtility] (minecraft.jar) 
	UCH	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCH	gud_lib{1.2.0.0} [GudLib] (gud_lib-1.2.0.0.jar) 
	UCH	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UCH	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCH	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.9.jar) 
	UCH	cheesemod{5.0} [§6Cheese Mod] ([1.11.2  1.11] Cheese mod v 5.0 by NuclearBanana.jar) 
	UCH	forgeendertech{1.11.2-2.1.3.0} [Forge Endertech] (ForgeEndertech-1.11.2-2.1.3.0-build.0067.jar) 
	UCH	adchimneys{1.11.2-2.0.12.0} [Advanced Chimneys] (AdChimneys-1.11.2-2.0.12.0-build.0069.jar) 
	UCH	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCH	animania{1.2.1} [Animania] (animania-1.11.2-1.2.1.jar) 
	UCH	appletrees{V2} [Apple Trees] (AppleTrees-1.11.2-V2.jar) 
	UCH	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.11.2-1.1.7.jar) 
	UCH	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCH	jei{4.5.0.293} [Just Enough Items] (jei_1.11.2-4.5.0.293.jar) 
	UCH	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UCH	betterwithmods{1.2.9-1.11.2} [Better With Mods] (Better With Mods-1.2.38-1.11.2.jar) 
	UCH	betterwithaddons{@VERSION@} [Better with Addons] (Better With Addons-0.17.jar) 
	UCH	betterachievements{0.4.4.17} [Better Achievements] (BetterAchievements-1.11.2-0.4.4.17.jar) 
	UCH	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide-API-1.11.2-2.1.1-52.jar) 
	UCH	bloodmagic{1.11-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.11-80.jar) 
	UCH	badwithernocookie{1.0} [Bad Wither No Cookie!] (bwncrldd-1.0.jar) 
	UCH	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCH	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCH	chesttransporter{2.7.9} [Chest Transporter] (ChestTransporter-1.11.2-2.7.9.jar) 
	UCH	claybucket{1.1} [Clay Bucket] (ClayBucket-1.11-1.0.jar) 
	UCH	coffeespawner{1.0.1} [Coffee Spawner] (CoffeeSpawner-1.11.2-1.0.1.jar) 
	UCH	cyclopscore{0.10.6} [Cyclops Core] (CyclopsCore-1.11.2-0.10.6.jar) 
	UCH	colossalchests{1.6.2} [Colossal Chests] (ColossalChests-1.11.2-1.6.2.jar) 
	UCH	cookingforblockheads{5.3.21} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.21.jar) 
	UCH	coralreef{1.0} [Coral Reef] (CoralReef-1.4.jar) 
	UCH	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCH	craftingcraft{5.1.1} [CraftingCraft] (CraftingCraft_1.11-5.1.1.jar) 
	UCH	eleccore{1.7.425} [ElecCore] (ElecCore-1.11-1.7.425.jar) 
	UCH	craftingtableiv{1.0} [CraftingTable-IV] (CraftingTableIV-1.4.113.jar) 
	UCH	craftingtweaks{7.1.9} [Crafting Tweaks] (CraftingTweaks_1.11.2-7.1.9.jar) 
	UCH	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.7.4 mc1.11.2.jar) 
	UCH	d3core{1.3.0.66} [DÂ³Core] (D3Core-1.11.2-1.3.0.66.jar) 
	UCH	dailies{1.11.2-6} [Bailey's Dailies] (dailies-1.11.2-6.jar) 
	UCH	defaultoptions{8.2.2} [Default Options] (DefaultOptions_1.11.2-8.2.2.jar) 
	UCH	diamondglass{1.11.2-1.2.0} [Diamond Glass] (diamondglass-1.11.2-1.2.0.jar) 
	UCH	durabilityshow{4.1.1} [Durability Show] (Durability Show-1.11.2-4.1.1.jar) 
	UCH	easybreeding{4.1.0} [EasyBreeding] (easybreading-1.11.2-4.1.0.jar) 
	UCH	emvi{2.2} [Emergent Villages] (EmergentVillages-2.2.jar) 
	UCH	enderpay{0.3} [EnderPay] (enderpay-1.11.2-0.0.3.jar) 
	UCH	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCH	extrarails{1.2.1} [Extra Rails] (ExtraRails-1.11-1.2.1.jar) 
	UCH	ezstorage{2.4.1} [EZStorage 2] (ezstorage-2.4.1-[1.11.2].jar) 
	UCH	farseek{2.1} [Farseek] (Farseek-1.11-2.1.jar) 
	UCH	fasterladderclimbing{0.1-118} [Faster Ladder Climbing] (FasterLadderClimbing-1.11-0.1-118.jar) 
	UCH	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCH	felling{1.1} [Felling] (felling-1.1.jar) 
	UCH	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCH	limelib{1.5.4} [LimeLib] (limelib-1.11.2-1.5.4.jar) 
	UCH	furnus{1.93} [Furnus] (furnus-1.11.2-1.93.jar) 
	UCH	giacomos_bookshelf{1.1} [Giacomo's Bookshelves Mod] (GiacomosBookshelf-1.11.2-1.1.jar) 
	UCH	fishing{1.5.1} [Fishing Net Mod] (GiacomosFishingNet-1.11.2-1.5.1.jar) 
	UCH	giacomosfoundry{1.3.12} [Giacomo's Foundry] (GiacomosFoundry-1.11.2-1.3.12.jar) 
	UCH	gravestone{1.7.4} [Gravestone Mod] (gravestone-1.7.4_.jar) 
	UCH	gud_coolers{2.0.0.4} [Coolers] (gud_coolers-2.0.0.4.jar) 
	UCH	hammerz{1.11.2-0.1.4.27} [Hammerz] (hammerz-1.11.2-0.1.4.27.jar) 
	UCH	hopperducts{1.4.9.2} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.2.jar) 
	UCH	furniture{1.1.3} [How 'Bout That Furniture] (HowBoutThatFurniture-1.2.1.jar) 
	UCH	waila{1.8.15} [Waila] (Hwyla-1.8.15-B29_1.11.jar) 
	UCH	inventorytweaks{1.63+dev.92.4367155} [Inventory Tweaks] (InventoryTweaks-1.63+dev.92.jar) 
	UCE	ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar) 
	UCH	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCH	largeveins{@VERSION@} [Large Veins] (LargeVeins-1.11-1.0.0.jar) 
	UCH	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UCH	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (literalascension-1.11.2-1.0.2.2.jar) 
	UCH	littletiles{1.4.8} [LittleTiles] (LittleTiles v1.4.12 mc1.11.2.jar) 
	UCH	lumberjack{1.0} [lumberjack] (Lumberjack-1.11.2-1.3.1.48.jar) 
	UCH	minecolonies{1.11.2-0.8.3136} [MineColonies] (minecolonies-universal-1.11.2-0.8.3136.jar) 
	UCH	examplemod{1.0} [examplemod] (missing_pieces-1.11.2-4.3.0.jar) 
	UCH	missing_pieces{4.3.0} [Missing Pieces] (missing_pieces-1.11.2-4.3.0.jar) 
	UCH	morefuelsmod-1.11.x{1.6.0} [§4More Fuels Mod] (morefuelsmod-1.11.x-1.6.0.jar) 
	UCH	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.11.2.jar) 
	UCH	multimine{1.5.7} [Multi Mine] (MultiMine-1.11.2.jar) 
	UCH	mxtune{0.4.0-dev.24} [mxTune] (mxtune-1.11.2-0.4.0-dev.24.jar) 
	UCH	mycommands{1.11.2-02} [MY Commands] (MyCommands-1.11.2-02.jar) 
	UCH	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.11.2-1.3.0.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCH	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCH	notenoughwands{1.5.5} [Not Enough Wands] (notenoughwands-1.1x-1.5.5.jar) 
	UCH	opframe{1.4.0} [OnlinePictureFrame] (OnlinePicFrame v1.4.0 mc1.11.2.zip) 
	UCH	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCH	plants{0.8.5} [Plants] (Plants-1.11.2-beta-0.8.5.jar) 
	UCH	shetiphiancore{3.4.5} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.6.jar) 
	UCH	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCH	pulver{@VERSION@} [Pulver] (Pulver-1.11.x-1.0.jar) 
	UCH	railsplus{1.0.0} [Rails Plus] (railsplus-1.0.1.jar) 
	UCH	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	UCH	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCH	refinedrelocation{3.1.14} [Refined Relocation] (RefinedRelocation-mc1.11.2-3.1.14.jar) 
	UCH	reptilemod{3.6.2} [Reptile Mod] (reptilemod-1.11.2-3.6.2-68.jar) 
	UCH	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCH	rustic{0.3.7} [Rustic] (rustic-0.3.7.jar) 
	UCH	sem{1.6.0b} [Steam Engines Mod] (SEM - mc1_11_2-1.6.0 beta.jar) 
	UCH	semmagie{1.6.0b} [Steam Engines Mod - Magie Addon] (SEM - mc1_11_2-1.6.0 beta.jar) 
	UCH	simplecorn{2.2.0} [Simple Corn] (simpleCorn1.11.2-2.2.0.jar) 
	UCH	storagenetwork{1.0.0} [Simple Storage Network] (SimpleStorageNetwork-1.11.2-1.0.5.jar) 
	UCH	stellarapi{0.6.4.1.3} [Stellar API] (Stellar API-0.6.4.1.3.jar) 
	UCH	stellarsky{0.6.5.1.4} [Stellar Sky] (Stellar Sky-0.6.5.1.4.jar) 
	UCH	storageboats{2.0} [Storage Boats Mod] (StorageBoats-2.4.jar) 
	UCH	storagedrawers{1.11.2-4.2.10} [Storage Drawers] (StorageDrawers-1.11.2-4.2.10.jar) 
	UCH	strait{1.11-0.3} [Strait] (strait-1.11-0.3.jar) 
	UCH	streams{0.3} [Streams] (Streams-1.11-0.3.jar) 
	UCH	structuredcrafting{0.1.8} [Structured Crafting] (StructuredCrafting-1.11.2-0.1.8.jar) 
	UCH	terraqueous{1.3.14} [Terraqueous] (terraqueous-1.11.0-1.3.14.jar) 
	UCH	tesla{1.3.0.52} [TESLA] (Tesla-1.11-1.3.0.52.jar) 
	UCH	tinker_io{release 2.5.2c} [Tinker I/O] (tinker_io-1.11.2-release 2.5.2c.jar) 
	UCH	toolbelt{1.6.1} [Tool Belt] (ToolBelt-1.11.2-1.6.1.jar) 
	UCH	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (torohealth-1.11.2-11.jar) 
	UCH	toroquest{1.11.2-4.0} [ToroQuest] (toroquest-1.11.2-4.0.jar) 
	UCH	underphangables{1.0.4} [Underp Hangables] (underphangables-1.11.2-1.0.4.jar) 
	UCH	underwaterutilities{@VERSION@} [Underwater Utilities] (UnderwaterUtilities-1.11.2-1.2.5.jar) 
	UCH	uniquecrops{0.1.45} [Unique Crops] (uniquecrops-1.11.2-0.1.45.jar) 
	UCH	usefulnullifiers{1.3.5} [Useful Nullifiers] (usefulnullifiers-1.3.5.jar) 
	UCH	vending{1.4.3.1} [Vending] (vending-1.11.2-1.4.3.1.jar) 
	UCH	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCH	waddles{0.5.3} [Waddles] (Waddles-1.11.2-0.5.3.jar) 
	UCH	wailaharvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.10.jar) 
	UCH	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	Loaded coremods (and transformers): 
DummyPlugin (ForgeEndertech-1.11.2-2.1.3.0-build.0067.jar)
  
Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
ItemPatchingLoader (ItemPhysic Full 1.4.6 mc1.11.2.jar)
  com.creativemd.itemphysic.ItemTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.92.jar)
  invtweaks.forge.asm.ContainerTransformer
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
GudLib (gud_lib-1.2.0.0.jar)
  net.gudenau.lib.core.ClientTransformer
FarseekCoreMod (Farseek-1.11-2.1.jar)
  farseek.core.FarseekClassTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
CreativePatchingLoader (CreativeCore v1.7.4 mc1.11.2.jar)
  
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LittlePatchingLoader (LittleTiles v1.4.12 mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.6.jar)
  shetiphian.core.asm.ClassTransformer
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
MMFMLCorePlugin (MultiMine-1.11.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
literalascension (literalascension-1.11.2-1.0.2.2.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	d3core: Debug: false Silliness: false AprilFools: false PastPost:false
```

**Comment by DaedalusGame** [comment]
ungh ok, i'll release another version as soon as i can, i found some bugs related to my capabilities when i was testing earlier

**Comment by DaedalusGame** [comment]
Also the way to currently resolve this without downgrading is to turn off random japanese mob spawns
