### ISSUE TITLE
Server Crash with newest Forge

### ISSUE THREAD

**Issue by Burgersim** [DaedalusGame/BetterWithAddons#31]
In SMP the Mod in my Modpack seems to work perfectly fine, but when trying to start a Server with my Modpack, I get an Error during Mod Construction:

```
---- Minecraft Crash Report ----
 
 WARNING: coremods are present:
LoadingPlugin (Quark-r1.2-104.jar)
IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
IvToolkit (IvToolkit-1.3.3-1.12.jar)
 Contact their authors BEFORE contacting forge
 
 // There are four lights!
 
 Time: 06.08.17 14:06
 Description: Exception in server tick loop
 
 net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better with Addons (betterwithaddons)
 Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/ICustomModelLoader
 	at java.lang.Class.forName0(Native Method)
 	at java.lang.Class.forName(Unknown Source)
 	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:592)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 	at java.lang.reflect.Method.invoke(Unknown Source)
 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 	at java.lang.reflect.Method.invoke(Unknown Source)
 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
 	at java.lang.Thread.run(Unknown Source)
 Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.ICustomModelLoader
 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
 	at java.lang.ClassLoader.loadClass(Unknown Source)
 	at java.lang.ClassLoader.loadClass(Unknown Source)
 	... 35 more
 Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/IResourceManagerReloadListener
 	at java.lang.ClassLoader.defineClass1(Native Method)
 	at java.lang.ClassLoader.defineClass(Unknown Source)
 	at java.security.SecureClassLoader.defineClass(Unknown Source)
 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
 	... 37 more
 Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.IResourceManagerReloadListener
 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
 	at java.lang.ClassLoader.loadClass(Unknown Source)
 	at java.lang.ClassLoader.loadClass(Unknown Source)
 	... 41 more
 Caused by: java.lang.NullPointerException
 
 
 A detailed walkthrough of the error, its code path and all known details is as follows:
 ---------------------------------------------------------------------------------------
 
 -- System Details --
 Details:
 	Minecraft Version: 1.12
 	Operating System: Windows 7 (amd64) version 6.1
 	Java Version: 1.8.0_141, Oracle Corporation
 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 	Memory: 655083200 bytes (624 MB) / 844103680 bytes (805 MB) up to 1849688064 bytes (1764 MB)
 	JVM Flags: 0 total; 
 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 	FML: MCP 9.40 Powered by Forge 14.21.1.2443 30 mods loaded, 30 mods active
 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
 	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
 	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443-universal.jar) 
 	UC	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443-universal.jar) 
 	UC	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
 	UC	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
 	UC	tconstruct{1.12-2.7.2.15} [Tinkers' Construct] (TConstruct-1.12-2.7.2.15.jar) 
 	UC	immersiveengineering{0.12-70} [Immersive Engineering] (ImmersiveEngineering-0.12-70.jar) 
 	UC	betterwithmods{1.2.9-1.11.2} [Better With Mods] (BetterWithMods-1.12-2.0.2.jar) 
 	UC	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
 	UC	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
 	UE	betterwithaddons{@VERSION@} [Better with Addons] (Better With Addons-0.21hotfix.jar) 
 	UC	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
 	UC	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
 	UC	ceramics{1.12-1.3.2} [Ceramics] (Ceramics-1.12-1.3.2.jar) 
 	UC	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
 	UC	chiselsandbits{14.4} [Chisels & Bits] (chiselsandbits-14.4.jar) 
 	UC	covens{0.1-dev} [Covens] (covens-0.1-dev.jar) 
 	UC	crafttweaker{4.0.2} [CraftTweaker2] (CraftTweaker2-1.12-4.0.2.jar) 
 	UC	cucumber{1.0.0} [Cucumber] (cucumber[1.12]-1.0.0.jar) 
 	UC	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
 	UC	immersivepetroleum{1.1.3} [Immersive Petroleum] (immersivepetroleum-1.12-1.1.3.jar) 
 	UC	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
 	UC	mysticalagriculture{1.6.2} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.2.jar) 
 	UC	mysticalagradditions{1.2.2} [Mystical Agradditions] (mysticalagradditions[1.12]-1.2.2.jar) 
 	UC	nex{2.1.11.12} [NetherEx] (NetherEx-1.12-2.1.11.12.jar) 
 	UC	plustic{6.0.0.5} [PlusTiC] (plustic-6.0.0.5.jar) 
 	UC	reccomplex{1.4.4} [Recurrent Complex] (RecurrentComplex-1.4.4.jar) 
 	UC	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
 	UC	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
 	Loaded coremods (and transformers): 
 LoadingPlugin (Quark-r1.2-104.jar)
   vazkii.quark.base.asm.ClassTransformer
 IELoadingPlugin (ImmersiveEngineering-0.12-70.jar)
   blusunrize.immersiveengineering.common.asm.IEClassTransformer
 IvToolkit (IvToolkit-1.3.3-1.12.jar)
   
 	Pulsar/tconstruct loaded Pulses: 
 		- TinkerCommons (Enabled/Forced)
 		- TinkerWorld (Enabled/Not Forced)
 		- TinkerTools (Enabled/Not Forced)
 		- TinkerHarvestTools (Enabled/Forced)
 		- TinkerMeleeWeapons (Enabled/Forced)
 		- TinkerRangedWeapons (Enabled/Forced)
 		- TinkerModifiers (Enabled/Forced)
 		- TinkerSmeltery (Enabled/Not Forced)
 		- TinkerGadgets (Enabled/Not Forced)
 		- TinkerOredict (Enabled/Forced)
 		- TinkerIntegration (Enabled/Forced)
 		- TinkerFluids (Enabled/Forced)
 		- TinkerMaterials (Enabled/Forced)
 		- TinkerModelRegister (Enabled/Forced)
 		- chiselsandbitsIntegration (Enabled/Not Forced)
 
 	Profiler Position: N/A (disabled)
 	Is Modded: Definitely; Server brand changed to 'fml,forge'
 	Type: Dedicated Server (map_server.txt)`
```

Hope I can get help soon, I really want to play this Modpack with my friends ^^*

**Comment by DaedalusGame** [comment]
I'm investigating, but it's gonna take some time because it's not very logical and I have no pointers as to what's going on, because none of the exceptions are sourced in my code.

**Comment by Burgersim** [comment]
Thanks for looking into it, if you need more information, logs or something I can help you with, just tell me, I'll be happy to provide any help I can ^^

**Comment by DaedalusGame** [comment]
I've put the fix on curse
