### ISSUE TITLE
[CoL] [1.11.2] Recent BWM update crash

### ISSUE THREAD

**Issue by drakray** [DaedalusGame/BetterWithAddons#9]
https://pastebin.com/mgPT951f
`
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better with Addons (betterwithaddons)
Caused by: java.lang.NoSuchMethodError: betterwithmods.common.registry.bulk.manager.MillManager.addRecipe(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;[Ljava/lang/Object;)V
	at betterwithaddons.interaction.InteractionBWM.init(InteractionBWM.java:88)
	at betterwithaddons.interaction.ModInteractions.init(ModInteractions.java:42)
	at betterwithaddons.BetterWithAddons.init(BetterWithAddons.java:88)`

Minecraft 1.11.2
Forge 2310
BWM 1.2.16 (probably 1.2.15 too)
BWA 0.7

**Comment by DaedalusGame** [comment]
ah yes, recipe registration changed, will fix when i get up.
